### ISSUE TITLE
make roslaunch_folder a global variable

### ISSUE THREAD

**Issue by mzhouURI** [GSO-soslab/mvp_gui#12]
line 57 in the `route_systems.py`, we will set the path to the default folder every time.
We need to make `roslaunch folder` a global variable.
 so after i change it, the text box will show the most recent folder i typed.

**Comment by altyi** [comment]
`roslaunch_folder` is set to `roslaunch_folder_default` when the server starts. It is a global variable that takes on the value of the user input.
